
swagger: '2.0'
info:
  description: Api calls of Question/Answer Microservice
  title: Question Answer Microservice
  version: v2
schemes:
  - http
basePath: /
tags:
- name: "question"
  description: "Everything about Questions"
- name: "answer"
  description: "Everything about Answers"  
paths:
  /question:
    post:
      tags:
      - "question"
      summary: "Add a new question"
      description: "Add question details / Update question details"
      operationId: "addQuestion"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Question object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Question"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Question"
        405:
          description: "Invalid input"
    get:
      tags:
      - "question"
      summary: "Get all questions"
      description: "Show all questions"
      operationId: "showQuestions"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Question"
        400:
          description: "Invalid status value"
  /question/{questionId}:
    get:
      tags:
      - "question"
      summary: "Show a particular question"
      description: ""
      operationId: "getQuestionById"
      produces:
      - "application/json"
      parameters:
      - name: "questionId"
        in: "path"
        description: "QuestionId"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
              $ref: "#/definitions/Question"
        400:
          description: "Invalid id value"
    
    delete:
      tags:
      - "question"
      summary: "Deletes a question"
      description: ""
      operationId: "deleteQuestion"
      produces:
      - "application/json"
      parameters:
      - name: "questionId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Invalid ID supplied"
        404:
          description: "Question not found"
  
  /answer:
    post:
      tags:
      - "answer"
      summary: "Add a new answer"
      description: "Add question details"
      operationId: "addAnswer"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Answer object that needs to be added to the system"
        required: true
        schema:
          $ref: "#/definitions/Answer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Answer"
        405:
          description: "Invalid input" 
  /answer/{id}:        
    get:
      tags:
      - "answer"
      summary: "Get all answers for a question"
      description: "Show all answers for a particular question pass questionId"
      operationId: "showAnswersById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "QuestionId"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Answer"
        400:
          description: "Invalid id value"  
    delete:
      tags:
      - "answer"
      summary: "Deletes a answer"
      description: "Delete a answer by passing answerId"
      operationId: "deleteAnswer"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "AnswerId"
        required: true
        type: "string"
      responses:
        200:
          description: OK
        400:
          description: "Invalid ID supplied"
        404:
          description: "Answer not found"  
          
definitions:
  Question:
    type: "object"
    properties:
      questionId:
        type: "integer"
        format: "int64"
      question:
        type: "string"
        example: "what is the rating" 
      feedbackType:
        type: "string"
        example: "participated"
      answerType:
        type: "string"
        example: "free text answer"  
      totalAnswers:
        type: "integer"
        format: "int64"  
  Answer:
    type: "object"
    properties:
      answerId:
        type: "integer"
        format: "int64"
      answer:
        type: "string"
        example: "Rating is 4" 
      questionId:
        type: "integer"
        format: "int64" 
       

  